### PR TITLE
fix(py): fix SSL for python > 3.8

### PR DESCRIPTION
**Pull request by timothe-ignace**
Fix error "ssl.SSLError: Cannot create a client socket with a PROTOCOL_TLS_SERVER context " display on Python3.10

### CODE REVIEW

**Comment by MrAsterisco** [comment]
Hey @timo8042 ! Thanks for creating this! 

Would you mind pointing to the documentation you used to get to this change? What I'm a bit worried about is compatibility with the previous versions of Pythons, which worked with version 3.8. If we merge this and it's not compatible with the existing installation, people will get _angry_. 😃

**Comment by LeLunZ** [comment]
@MrAsterisco I have the same problem as @timo8042 
With newer python versions its not working anymore.

But I just installed 3.8 for testing, and his code also works for me on 3.8 and 3.11.

Here more information about the issue:
CLIENT_AUTH seems to set PROTOCOL_TLS_SERVER which is used for servers (?) see [here](https://docs.python.org/3/library/ssl.html). I haven't worked with the ssl library. But here is a issue about the confusing behaviour: https://github.com/python/cpython/issues/96972
I think we need to set SERVER_AUTH instead of CLIENT_AUTH, because we want a (mqtt) client not a server (?)

These lines are needed because SERVER_AUTH sets other defaults.
```python
        ssl_context.check_hostname = False
        ssl_context.verify_mode = ssl.CERT_NONE
```


General question:
why not just upgrade the python package and the homebridge package. Users with python3.8 can always install the old version if they want.  (and 3.8 end of life is in 5 months) 
I thinks it would be better that new users have a seamless experience with installing the package, and dont need to build python3.8 from source.
Its more of a theoretical question, as I did test it on 3.8 and it worked.

**Comment by MrAsterisco** [comment]
@LeLunZ well... when I raised that comment, the situation was different, but my concerns were never answered 😃 I'm okay with merging this now, also considering you tested it (which is great, btw, thank you!).

I will move forward with the merge. We will then also need a corresponding PR on the Homebridge plugin.

**Review by MrAsterisco — APPROVED** [review]

**Comment by MrAsterisco** [comment]
@LeLunZ I cannot tag you on the plugin repo, because you never contributed there. I opened [a PR](https://github.com/MrAsterisco/homebridge-hisense-tv/pull/55) that you can use to test whether the plugin works with the updated Python package.

**Pull request merged**
